### ISSUE TITLE
unable to install it on ubuntu 12.04 lts

### ISSUE THREAD

**Issue by moses-gangipogu** [seamusabshere/mysql2xxxx#1]
root@ubuntu:~# gem install mysql2xxxx

Building native extensions.  This could take a while...
ERROR:  Error installing mysql2xxxx:
    ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:13:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/atomic-1.1.15 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/atomic-1.1.15/ext/gem_make.out

**Comment by seamusabshere** [comment]
hey @moses-gangipogu I think this is related to the `atomic` gem... check out [this stackoverflow answer](http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror) about how to fix.

the gist is you need the ruby development headers installed on your machine.

**Comment by moses-gangipogu** [comment]
kk thanks for ur feedback
